### ISSUE TITLE
How can we find the from address coins?

### ISSUE THREAD

**Issue by Cindy1122334455** [alecalve/python-bitcoin-blockchain-parser#58] opened 2018-09-28 00:26 UTC
We cannot find the logic involving with "from address coins"  in your parsing tool. How can we find the from address coins? Is it in the previous transaction hash' s output file?

**Comment by alecalve** [comment] 2018-10-02 09:31
Duplicate of https://github.com/alecalve/python-bitcoin-blockchain-parser/issues/44

**Closed by alecalve** 2018-10-02 09:31 UTC
